"""Read the per-account ``seed`` from the running ``Weixin.exe`` process.

The seed is an 8-12 digit integer generated by WeChat and held in process
memory. It is the only unknown required to derive the emoticon AES key.

This module is Windows-only and uses only ``ctypes`` (no third-party deps).
Importing it on other platforms is safe; calling into it raises ``RuntimeError``.
"""

from __future__ import annotations

import ctypes
import re
import sys
from typing import Iterator, List, Optional, Set, Tuple

IS_WINDOWS = sys.platform == "win32"

SEED_RE = re.compile(rb"(?<![0-9])(\d{8,12})(?![0-9])")
SEED_MIN = 100_000_000
SEED_MAX = 4_000_000_000

PROCESS_QUERY_INFORMATION = 0x0400
PROCESS_VM_READ = 0x0010
TH32CS_SNAPPROCESS = 0x00000002
MEM_COMMIT = 0x1000
MEM_PRIVATE = 0x20000
PAGE_READABLE = {0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80}
PAGE_WRITABLE = {0x04, 0x08, 0x40}
MAX_REGION = 200 * 1024 * 1024
CHUNK = 32 * 1024 * 1024
MAX_USER_ADDRESS = 0x7FFFFFFFFFFF
INVALID_HANDLE = ctypes.c_void_p(-1).value


class MEMORY_BASIC_INFORMATION(ctypes.Structure):
    _fields_ = [
        ("BaseAddress", ctypes.c_uint64),
        ("AllocationBase", ctypes.c_uint64),
        ("AllocationProtect", ctypes.c_uint32),
        ("_pad1", ctypes.c_uint32),
        ("RegionSize", ctypes.c_uint64),
        ("State", ctypes.c_uint32),
        ("Protect", ctypes.c_uint32),
        ("Type", ctypes.c_uint32),
        ("_pad2", ctypes.c_uint32),
    ]


class PROCESSENTRY32W(ctypes.Structure):
    _fields_ = [
        ("dwSize", ctypes.c_uint32),
        ("cntUsage", ctypes.c_uint32),
        ("th32ProcessID", ctypes.c_uint32),
        ("th32DefaultHeapID", ctypes.c_void_p),
        ("th32ModuleID", ctypes.c_uint32),
        ("cntThreads", ctypes.c_uint32),
        ("th32ParentProcessID", ctypes.c_uint32),
        ("pcPriClassBase", ctypes.c_long),
        ("dwFlags", ctypes.c_uint32),
        ("szExeFile", ctypes.c_wchar * 260),
    ]


if IS_WINDOWS:
    _kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    _kernel32.OpenProcess.restype = ctypes.c_void_p
    _kernel32.OpenProcess.argtypes = [ctypes.c_uint32, ctypes.c_int, ctypes.c_uint32]
    _kernel32.CloseHandle.argtypes = [ctypes.c_void_p]
    _kernel32.ReadProcessMemory.restype = ctypes.c_int
    _kernel32.ReadProcessMemory.argtypes = [
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_size_t,
        ctypes.POINTER(ctypes.c_size_t),
    ]
    _kernel32.VirtualQueryEx.restype = ctypes.c_size_t
    _kernel32.VirtualQueryEx.argtypes = [
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_void_p,
        ctypes.c_size_t,
    ]
    _kernel32.CreateToolhelp32Snapshot.restype = ctypes.c_void_p
    _kernel32.CreateToolhelp32Snapshot.argtypes = [ctypes.c_uint32, ctypes.c_uint32]
    _kernel32.Process32FirstW.restype = ctypes.c_int
    _kernel32.Process32FirstW.argtypes = [ctypes.c_void_p, ctypes.POINTER(PROCESSENTRY32W)]
    _kernel32.Process32NextW.restype = ctypes.c_int
    _kernel32.Process32NextW.argtypes = [ctypes.c_void_p, ctypes.POINTER(PROCESSENTRY32W)]
else:  # pragma: no cover - exercised only on non-Windows
    _kernel32 = None


def _require_windows() -> None:
    if not IS_WINDOWS:
        raise RuntimeError("process memory scanning is only supported on Windows")


def list_pids(image_name: str = "Weixin.exe") -> List[int]:
    """Return PIDs of running processes whose executable matches *image_name*."""
    _require_windows()
    target = image_name.lower()
    pids: List[int] = []
    snapshot = _kernel32.CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)
    if not snapshot or snapshot == INVALID_HANDLE:
        return pids
    try:
        entry = PROCESSENTRY32W()
        entry.dwSize = ctypes.sizeof(PROCESSENTRY32W)
        ok = _kernel32.Process32FirstW(snapshot, ctypes.byref(entry))
        while ok:
            if entry.szExeFile.lower() == target:
                pids.append(int(entry.th32ProcessID))
            ok = _kernel32.Process32NextW(snapshot, ctypes.byref(entry))
    finally:
        _kernel32.CloseHandle(snapshot)
    return pids


def _open_process(pid: int) -> Optional[int]:
    handle = _kernel32.OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, False, pid)
    return handle or None


def _read(handle: int, address: int, size: int) -> Optional[bytes]:
    buffer = ctypes.create_string_buffer(size)
    read = ctypes.c_size_t(0)
    ok = _kernel32.ReadProcessMemory(
        handle, ctypes.c_void_p(address), buffer, size, ctypes.byref(read)
    )
    if not ok:
        return None
    return buffer.raw[: read.value]


def iter_regions(handle: int, writable_only: bool = False) -> Iterator[Tuple[int, int]]:
    """Yield ``(base, size)`` of readable committed regions of a process."""
    address = 0
    mbi = MEMORY_BASIC_INFORMATION()
    while address < MAX_USER_ADDRESS:
        ok = _kernel32.VirtualQueryEx(
            handle, ctypes.c_void_p(address), ctypes.byref(mbi), ctypes.sizeof(mbi)
        )
        if ok == 0:
            break
        if (
            mbi.State == MEM_COMMIT
            and mbi.Protect in PAGE_READABLE
            and 0 < mbi.RegionSize < MAX_REGION
        ):
            if not writable_only or (mbi.Type == MEM_PRIVATE and mbi.Protect in PAGE_WRITABLE):
                yield mbi.BaseAddress, mbi.RegionSize
        next_address = mbi.BaseAddress + mbi.RegionSize
        if next_address <= address:
            break
        address = next_address


def scan_seed_candidates(
    pids: Optional[List[int]] = None, image_name: str = "Weixin.exe"
) -> Set[int]:
    """Scan WeChat process memory and return candidate seed integers."""
    _require_windows()
    if pids is None:
        pids = list_pids(image_name)
    seeds: Set[int] = set()
    for pid in pids:
        handle = _open_process(pid)
        if not handle:
            continue
        try:
            for base, size in iter_regions(handle, writable_only=True):
                offset = 0
                tail = b""
                while offset < size:
                    current = min(CHUNK, size - offset)
                    chunk = _read(handle, base + offset, current)
                    if chunk:
                        blob = tail + chunk
                        for match in SEED_RE.finditer(blob):
                            value = int(match.group(0))
                            if SEED_MIN < value < SEED_MAX:
                                seeds.add(value)
                        tail = blob[-64:]
                    else:
                        tail = b""
                    offset += current
        finally:
            _kernel32.CloseHandle(handle)
    return seeds
